### ISSUE TITLE
Atom install error

### ISSUE THREAD

**Issue by e-e** [PrestonKnopp/language-gdscript#17]
Attempting to install from the editor results in the following error:

[install-error.txt](https://github.com/PrestonKnopp/language-gdscript/files/3242983/install-error.txt)

**Comment by PrestonKnopp** [comment]
Hi, sorry about the late response. Can you try running `xcode-select --install` and then reinstall the plugin?

If needed additionally run `xcode-select --reset`. If Xcode path hasn't modified before you won't need to run the reset command.

**Comment by PrestonKnopp** [comment]
Hey just bumping this issue, has the above remedied the install error?

I wonder if it would be best to upload a prebuilt binary for macOS as is done for Windows.

**Comment by thomaskeschl** [comment]
I can verify that running both the `--install` and `--reset` commands allowed me to install the plugin after a similar error. Additionally, I had to run `sudo xcodebuild -license` in order to agree to the license before xcode would run.

After completing those steps, the application worked just fine. If there is an option to prebuild the plugin and distribute the binary that will work with apm, that would probably be best to do from the end user perspective. Just food for thought.

**Comment by PrestonKnopp** [comment]
Awesome, thank you for verifying and for the food for thought. I am now planning on distributing prebuilt macOS binaries and I'll keep this issue open until I get around to it.

**Comment by BrandonDyer64** [comment]
Does it _need_ tree-sitter-gdscript? I don't have sudo access on my Mac and I'd like to be able to open Godot scripts with syntax highlighting

**Comment by PrestonKnopp** [comment]
@BrandonDyer64 It will going forward as I will be dropping the legacy text mate grammar.

I have now uploaded prebuilt mac binaries. If you have a chance could you try (re)installing the lang-gdscript package? It should now download the binaries and install without needing sudo access.
