### ISSUE TITLE
Add gdscript language server support

### ISSUE THREAD

**Issue by Geequlim** [PrestonKnopp/language-gdscript#24]
The gdscript language server is now intergrated in godot editor now.
As I know Atom Editor is also support the lsp.
Is it possiable to make the great editor to support gdscript language server ?

Here are some references may be related:
https://microsoft.github.io/language-server-protocol/
https://github.com/atom/atom-languageclient
https://github.com/godotengine/godot-vscode-plugin

**Comment by PrestonKnopp** [comment]
Awesome, I'm looking into this now.

**Comment by PrestonKnopp** [comment]
It's now up and working on the add-ls branch.

Nice work on the language server! :)

**Comment by Pewsplosions** [comment]
@PrestonKnopp This sounds pretty cool. Are you planning to wait to merge it to master for when 3.2 is stable? Or should I just plan to get the add-ls branch manually and install it instead of the one on the atom package list?

That godot vscode plugin seems sooo nice. I really don't want to switch editors though. :(

Thanks for the good work!

**Comment by PrestonKnopp** [comment]
@Pewsplosions Hey, thanks for your interest! I was planning on waiting, but it's a good idea to merge it to master soon as an opt-in feature and get some feedback.

I'll merge it later today and notify you here :)

**Comment by PrestonKnopp** [comment]
@Pewsplosions The language server client has been merged and is now live on atom!

Feel free to open new issues if you run into any problems. Happy coding :)
